const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const url = require('url');

const ROOT = path.resolve(__dirname, '../..');
const PUBLIC_DIR = path.join(ROOT, 'apps', 'web', 'public');
const DATA_DIR = path.join(ROOT, 'data');
const STORAGE_DIR = path.join(ROOT, 'storage', 'uploads');
const DB_PATH = path.join(DATA_DIR, 'db.json');
const PORT = Number(process.env.PORT || 5174);
const TOKENS = new Map();

const PERMISSIONS = [
  'pos.view','pos.create','pos.edit','pos.hold','pos.pay','pos.void','pos.refund','pos.transfer_table','pos.payment_correction',
  'reports.view','reports.export','admin.menu','admin.tables','admin.staff','admin.users','admin.roles','admin.settings','admin.payments','admin.printer','admin.branding','cloud.sync','backup.manage'
];
const CASHIER_PERMS = ['pos.view','pos.create','pos.edit','pos.hold','pos.pay'];
const MANAGER_PERMS = [...CASHIER_PERMS,'reports.view','reports.export','pos.void','pos.refund','pos.transfer_table','pos.payment_correction','admin.menu','admin.tables','admin.staff','admin.payments','admin.printer'];

function now() { return new Date().toISOString(); }
function uid(prefix = 'id') { return `${prefix}_${crypto.randomBytes(8).toString('hex')}`; }
function money(n) { return Math.round((Number(n) || 0) * 100) / 100; }
function ensureDir(p) { if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true }); }
function safeName(name) { return String(name || 'file').replace(/[^a-z0-9._-]/gi, '-').replace(/-+/g, '-').slice(0, 80); }
function sample(p) { return `/assets/img/sample/${p}`; }

function seedDb() {
  return {
    meta: { app: 'SwiftTill POS', version: '7.0.0-online-pos-operational-fixes', createdAt: now(), storage: 'local-json', deployment: 'online-cloud-github-render-neon-r2-print-agent-ready' },
    settings: {
      businessName: 'SwiftTill Demo Restaurant', legalName: 'SwiftTill Demo Restaurant', branchName: 'Main Branch', branchCode: 'MAIN', phone: '03XX-XXXXXXX', email: 'info@swifttill.local', website: '', address: 'Rawalpindi, Pakistan', city: 'Rawalpindi', country: 'Pakistan', currency: 'PKR', logoUrl: '/assets/img/swifttill-logo.png',
      taxEnabled: false, taxPercent: 0, serviceChargeEnabled: false, serviceChargePercent: 0, defaultDeliveryFee: 150,
      autoPrintReceipt: true, rememberPrintChoice: true, receiptWidth: '80mm', receiptCopies: 1, receiptHeader: 'Fresh food, fast billing', receiptFooter: 'Thank you. Visit again.', showLogoOnReceipt: true, showCustomerOnReceipt: true, showOrderTakerOnReceipt: true, showCashierOnReceipt: true, showPaymentBreakdown: true, showReprintLabel: true,
      reportTitle: 'Sales Report', reportFooter: 'Generated by SwiftTill POS', reportShowBranding: true, reportPaper: 'A4',
      managerPin: '1234', printerName: 'Windows Default Printer', onlineOnly: true, printMode: 'cloud-app-with-local-print-agent', localAgentUrl: 'http://127.0.0.1:9721/print', appWindowMode: 'pwa-or-edge-app-window',
      r2Mode: 'local-placeholder', r2BucketName: '', r2PublicUrl: '', cloudApiUrl: '', backupTarget: 'local-download-first-r2-later'
    },
    roles: [
      { id: 'role_admin', name: 'Admin', description: 'Full system control', permissions: PERMISSIONS, system: true, active: true },
      { id: 'role_manager', name: 'Manager', description: 'Operations, reports, menu and approvals', permissions: MANAGER_PERMS, system: true, active: true },
      { id: 'role_cashier', name: 'Cashier', description: 'Billing counter access', permissions: CASHIER_PERMS, system: true, active: true }
    ],
    users: [
      { id: 'usr_admin', name: 'Admin', email: 'admin@swifttill.local', password: 'admin123', roleIds: ['role_admin'], pin: '1234', active: true },
      { id: 'usr_manager', name: 'Manager', email: 'manager@swifttill.local', password: 'manager123', roleIds: ['role_manager'], pin: '2222', active: true },
      { id: 'usr_cashier', name: 'Cashier', email: 'cashier@swifttill.local', password: 'cashier123', roleIds: ['role_cashier'], pin: '1111', active: true }
    ],
    orderTakers: [
      { id: 'tak_ali', name: 'Ali Ahmed', active: true }, { id: 'tak_sara', name: 'Sara Khan', active: true }, { id: 'tak_bilal', name: 'Bilal Hassan', active: true }
    ],
    categories: [
      { id: 'cat_all', name: 'All Items', imageUrl: sample('all.svg'), active: true, sort: 0, system: true },
      { id: 'cat_burgers', name: 'Burgers', imageUrl: sample('burger.svg'), active: true, sort: 1 },
      { id: 'cat_pizza', name: 'Pizza', imageUrl: sample('pizza.svg'), active: true, sort: 2 },
      { id: 'cat_sides', name: 'Sides', imageUrl: sample('fries.svg'), active: true, sort: 3 },
      { id: 'cat_drinks', name: 'Drinks', imageUrl: sample('drink.svg'), active: true, sort: 4 },
      { id: 'cat_desserts', name: 'Desserts', imageUrl: sample('dessert.svg'), active: true, sort: 5 }
    ],
    items: [
      { id: 'itm_zinger', name: 'Zinger Burger', categoryId: 'cat_burgers', price: 650, imageUrl: sample('burger.svg'), active: true, soldOut: false, sort: 1, modifiers: [{ name: 'Cheese', price: 100 }, { name: 'Extra Patty', price: 220 }, { name: 'Extra Sauce', price: 60 }] },
      { id: 'itm_beef', name: 'Beef Burger', categoryId: 'cat_burgers', price: 750, imageUrl: sample('burger.svg'), active: true, soldOut: false, sort: 2, modifiers: [{ name: 'Cheese', price: 100 }, { name: 'Extra Patty', price: 260 }] },
      { id: 'itm_pizza', name: 'Pizza Slice', categoryId: 'cat_pizza', price: 450, imageUrl: sample('pizza.svg'), active: true, soldOut: false, sort: 3, modifiers: [{ name: 'Extra Cheese', price: 120 }] },
      { id: 'itm_fries', name: 'Fries', categoryId: 'cat_sides', price: 300, imageUrl: sample('fries.svg'), active: true, soldOut: false, sort: 4, modifiers: [{ name: 'Mayo Dip', price: 50 }, { name: 'Garlic Dip', price: 70 }] },
      { id: 'itm_loaded', name: 'Loaded Fries', categoryId: 'cat_sides', price: 550, imageUrl: sample('loaded-fries.svg'), active: true, soldOut: false, sort: 5, modifiers: [{ name: 'Extra Cheese', price: 120 }] },
      { id: 'itm_coke', name: 'Coke', categoryId: 'cat_drinks', price: 180, imageUrl: sample('drink.svg'), active: true, soldOut: false, sort: 6, modifiers: [] },
      { id: 'itm_cupcake', name: 'Cup Cake', categoryId: 'cat_desserts', price: 280, imageUrl: sample('dessert.svg'), active: true, soldOut: false, sort: 7, modifiers: [] }
    ],
    deals: [
      { id: 'deal_family', name: 'Family Deal', price: 2100, imageUrl: sample('family-deal.svg'), active: true, sort: 1, description: '2 Burgers + Fries + 2 Drinks', items: [{ itemId: 'itm_zinger', qty: 2 }, { itemId: 'itm_fries', qty: 1 }, { itemId: 'itm_coke', qty: 2 }] },
      { id: 'deal_lunch', name: 'Lunch Combo', price: 950, imageUrl: sample('deal.svg'), active: true, sort: 2, description: 'Burger + Fries + Drink', items: [{ itemId: 'itm_zinger', qty: 1 }, { itemId: 'itm_fries', qty: 1 }, { itemId: 'itm_coke', qty: 1 }] }
    ],
    tables: Array.from({ length: 12 }, (_, i) => ({ id: `tbl_${i + 1}`, name: `T${i + 1}`, seats: i < 2 ? 2 : i < 8 ? 4 : 6, floor: 'Ground Floor', active: true, sort: i + 1 })),
    paymentMethods: [{ id: 'cash', name: 'Cash', active: true }, { id: 'card', name: 'Card', active: true }, { id: 'online', name: 'Online', active: true }],
    customers: [], orders: [], shifts: [], refunds: [], auditLogs: [], counters: { bill: 1000, z: 0 }
  };
}
function loadDb() { ensureDir(DATA_DIR); ensureDir(STORAGE_DIR); if (!fs.existsSync(DB_PATH)) saveDb(seedDb()); const db = JSON.parse(fs.readFileSync(DB_PATH, 'utf8')); migrateDb(db); return db; }
function saveDb(db) { ensureDir(DATA_DIR); fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2)); }
function migrateDb(db) {
  const seed = seedDb();
  for (const k of ['settings','paymentMethods','orders','shifts','refunds','auditLogs','counters','customers']) if (db[k] === undefined) db[k] = seed[k];
  if (!Array.isArray(db.roles)) db.roles = seed.roles;
  if (db.meta) db.meta.version = '7.0.0-online-pos-operational-fixes';
  for (const [k,v] of Object.entries(seed.settings)) if (db.settings[k] === undefined) db.settings[k] = v;
  for (const pm of seed.paymentMethods) if (!db.paymentMethods.find(x => x.id === pm.id)) db.paymentMethods.push(pm);
  if (Array.isArray(db.users)) db.users.forEach(u => { if (!Array.isArray(u.roleIds)) u.roleIds = u.role === 'ADMIN' ? ['role_admin'] : u.role === 'MANAGER' ? ['role_manager'] : ['role_cashier']; });
}
function userPermissions(db, user) { const set = new Set(); for (const rid of user.roleIds || []) { const role = db.roles.find(r => r.id === rid && r.active); if (role) (role.permissions || []).forEach(p => set.add(p)); } return [...set]; }
function hasPerm(db, user, perm) { return userPermissions(db, user).includes(perm); }
function requirePerm(db, user, perm) { if (!hasPerm(db, user, perm)) throw Object.assign(new Error(`Permission required: ${perm}`), { status: 403 }); }
function audit(db, user, action, details = {}) { db.auditLogs.unshift({ id: uid('aud'), action, userId: user?.id || 'system', userName: user?.name || 'System', details, createdAt: now() }); db.auditLogs = db.auditLogs.slice(0, 1000); }
function parseBody(req) { return new Promise((resolve, reject) => { let body = ''; req.on('data', c => { body += c; if (body.length > 20 * 1024 * 1024) reject(new Error('Payload too large')); }); req.on('end', () => { if (!body) return resolve({}); try { resolve(JSON.parse(body)); } catch { reject(new Error('Invalid JSON body')); } }); }); }
function send(res, status, data, headers = {}) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', ...headers }); res.end(JSON.stringify(data, null, 2)); }
function sendText(res, status, text, type = 'text/plain; charset=utf-8', headers = {}) { res.writeHead(status, { 'Content-Type': type, ...headers }); res.end(text); }
function getUserFromReq(req, db) { const h = req.headers.authorization || ''; const token = h.startsWith('Bearer ') ? h.slice(7) : null; const s = token && TOKENS.get(token); return s ? db.users.find(u => u.id === s.userId && u.active) : null; }
function requireAuth(req, db) { const u = getUserFromReq(req, db); if (!u) throw Object.assign(new Error('Unauthorized'), { status: 401 }); return u; }
function requireManager(db, pin) { if (!pin || pin !== db.settings.managerPin) throw Object.assign(new Error('Manager PIN required'), { status: 403 }); }
function totals(order) { const subtotal = money((order.lines || []).reduce((s, l) => s + ((Number(l.price) || 0) + (l.modifiers || []).reduce((a, m) => a + Number(m.price || 0), 0)) * Number(l.qty || 0), 0)); const deliveryFee = money(order.deliveryFee || 0); let discount = 0; if (order.discountType === 'PERCENT') discount = subtotal * Math.max(0, Math.min(100, Number(order.discountValue) || 0)) / 100; if (order.discountType === 'FIXED') discount = Number(order.discountValue) || 0; discount = money(Math.min(Math.max(0, discount), subtotal + deliveryFee)); return { subtotal, deliveryFee, discount, total: money(Math.max(0, subtotal + deliveryFee - discount)) }; }
function orderNumber(db) { db.counters.bill = Number(db.counters.bill || 1000) + 1; return String(db.counters.bill).padStart(6, '0'); }
function activeShift(db) { return db.shifts.find(s => s.status === 'OPEN') || null; }
function tableMap(db) { const open = db.orders.filter(o => ['OPEN','HELD'].includes(o.status) && o.type === 'DINE_IN' && o.tableId); return db.tables.map(t => { const order = open.find(o => o.tableId === t.id); return { ...t, busy: !!order, orderId: order?.id || null, orderNumber: order?.number || null, occupiedAt: order?.tableOccupiedAt || order?.createdAt || null, guests: order?.guests || 0 }; }); }
function publicUser(db, u) { const permissions = userPermissions(db, u); return { id: u.id, name: u.name, email: u.email, roleIds: u.roleIds || [], roles: (u.roleIds || []).map(id => db.roles.find(r => r.id === id)?.name).filter(Boolean), permissions }; }
function compactState(db, user) { return { user: publicUser(db, user), permissions: userPermissions(db, user), permissionCatalog: PERMISSIONS, settings: db.settings, roles: db.roles, categories: db.categories, items: db.items, deals: db.deals, tables: tableMap(db), orderTakers: db.orderTakers, paymentMethods: db.paymentMethods, users: db.users.map(u => ({ id: u.id, name: u.name, email: u.email, roleIds: u.roleIds || [], pin: u.pin || '', active: u.active })), openOrders: db.orders.filter(o => ['OPEN','HELD'].includes(o.status)).sort((a,b) => new Date(a.createdAt) - new Date(b.createdAt)), paidOrders: db.orders.filter(o => o.status === 'PAID').slice(-80).reverse(), refunds: db.refunds.slice(-80).reverse(), activeShift: activeShift(db), auditLogs: db.auditLogs.slice(0, 80) }; }
function between(date, from, to) { const t = new Date(date).getTime(); const a = from ? new Date(`${from}T00:00:00`).getTime() : 0; const b = to ? new Date(`${to}T23:59:59`).getTime() : Date.now() + 86400000; return t >= a && t <= b; }
function reportData(db, filters = {}) {
  const from = filters.from || '';
  const to = filters.to || '';
  const wantPayment = (filters.paymentMode || '').toLowerCase();
  const wantItem = filters.itemId || '';
  const wantCategory = filters.categoryId || '';
  const wantOrderType = filters.orderType || '';
  const wantCashier = filters.cashierId || '';
  const wantTaker = filters.orderTakerId || '';
  const wantShift = filters.shiftId || '';
  const discountOnly = filters.discountOnly === '1' || filters.discountOnly === true;
  const refundOnly = filters.refundOnly === '1' || filters.refundOnly === true;
  let paid = db.orders.filter(o => o.status === 'PAID' && between(o.paidAt || o.createdAt, from, to));
  paid = paid.filter(o => {
    if (wantPayment && !(o.payments || []).some(p => String(p.method || '').toLowerCase() === wantPayment)) return false;
    if (wantItem && !(o.lines || []).some(l => l.itemId === wantItem || l.dealId === wantItem)) return false;
    if (wantCategory && !(o.lines || []).some(l => l.categoryId === wantCategory)) return false;
    if (wantOrderType && o.type !== wantOrderType) return false;
    if (wantCashier && o.cashierId !== wantCashier) return false;
    if (wantTaker && o.orderTakerId !== wantTaker) return false;
    if (wantShift) {
      const shift = db.shifts.find(s => s.id === wantShift);
      if (!shift) return false;
      const t = new Date(o.paidAt || o.createdAt).getTime();
      const a = new Date(shift.openedAt).getTime();
      const b = shift.closedAt ? new Date(shift.closedAt).getTime() : Date.now() + 86400000;
      if (t < a || t > b) return false;
    }
    if (discountOnly && totals(o).discount <= 0) return false;
    return true;
  });
  let refunds = db.refunds.filter(r => between(r.createdAt, from, to));
  if (refundOnly) {
    const refundOrderIds = new Set(refunds.map(r => r.orderId));
    paid = paid.filter(o => refundOrderIds.has(o.id));
  }
  const gross = paid.reduce((s,o) => s + totals(o).subtotal + totals(o).deliveryFee, 0);
  const discounts = paid.reduce((s,o) => s + totals(o).discount, 0);
  const refundAmount = refunds.reduce((s,r) => s + Number(r.amount || 0), 0);
  const net = paid.reduce((s,o) => s + totals(o).total, 0) - refundAmount;
  const paymentWise = {}, itemWise = {}, categoryWise = {}, orderTypeWise = {}, discountWise = { count: 0, amount: 0 };
  for (const o of paid) {
    const ot = totals(o);
    orderTypeWise[o.type] = money((orderTypeWise[o.type] || 0) + ot.total);
    if (ot.discount > 0) { discountWise.count += 1; discountWise.amount = money(discountWise.amount + ot.discount); }
    for (const p of (o.payments || [])) paymentWise[p.method] = money((paymentWise[p.method] || 0) + Number(p.amount || 0));
    for (const l of (o.lines || [])) {
      const mods = (l.modifiers || []).reduce((a,m) => a + Number(m.price || 0), 0);
      const amount = ((Number(l.price) || 0) + mods) * (Number(l.qty) || 0);
      itemWise[l.name] ||= { item: l.name, category: db.categories.find(c => c.id === l.categoryId)?.name || (l.kind === 'DEAL' ? 'Deals' : 'Uncategorized'), qty: 0, sales: 0 };
      itemWise[l.name].qty += Number(l.qty) || 0;
      itemWise[l.name].sales = money(itemWise[l.name].sales + amount);
      const cat = itemWise[l.name].category;
      categoryWise[cat] = money((categoryWise[cat] || 0) + amount);
    }
  }
  const shiftForSummary = wantShift ? db.shifts.find(s => s.id === wantShift) : activeShift(db);
  const cashSalesForSummary = paymentWise.Cash || 0;
  const openingCashForSummary = shiftForSummary ? Number(shiftForSummary.openingCash || 0) : 0;
  const expectedCashForSummary = money(openingCashForSummary + cashSalesForSummary);
  return {
    range: { from, to },
    filters,
    shiftSummary: { shiftId: shiftForSummary?.id || '', openingCash: money(openingCashForSummary), cashSales: money(cashSalesForSummary), expectedCash: expectedCashForSummary, countedCash: shiftForSummary?.countedCash ?? null, difference: shiftForSummary?.difference ?? null },
    summary: { orders: paid.length, gross: money(gross), discounts: money(discounts), refunds: money(refundAmount), net: money(net), averageBill: paid.length ? money(net / paid.length) : 0 },
    paymentWise,
    itemWise: Object.values(itemWise).sort((a,b) => b.sales - a.sales),
    categoryWise,
    orderTypeWise,
    discountWise,
    refunds,
    voidOrders: db.orders.filter(o => o.status === 'VOID' && between(o.voidedAt || o.createdAt, from, to)),
    orders: paid.map(o => ({ number: o.number, date: o.paidAt, type: o.type, table: db.tables.find(t => t.id === o.tableId)?.name || '', customer: o.customerName || '', mobile: o.mobile || '', cashier: o.cashierName || '', orderTaker: o.orderTakerName || '', subtotal: totals(o).subtotal, discount: totals(o).discount, deliveryFee: totals(o).deliveryFee, total: totals(o).total, payments: (o.payments || []).map(p => `${p.method}:${p.amount}`).join(', ') }))
  };
}
function buildReceipt(db, order) { const t = totals(order); const table = db.tables.find(x => x.id === order.tableId)?.name || ''; return { business: db.settings.businessName, legalName: db.settings.legalName, branchName: db.settings.branchName, branchCode: db.settings.branchCode, phone: db.settings.phone, email: db.settings.email, website: db.settings.website, address: db.settings.address, city: db.settings.city, country: db.settings.country, logoUrl: db.settings.logoUrl, header: db.settings.receiptHeader, footer: db.settings.receiptFooter, receiptWidth: db.settings.receiptWidth, receiptCopies: db.settings.receiptCopies, showLogoOnReceipt: db.settings.showLogoOnReceipt, showCustomerOnReceipt: db.settings.showCustomerOnReceipt, showOrderTakerOnReceipt: db.settings.showOrderTakerOnReceipt, showCashierOnReceipt: db.settings.showCashierOnReceipt, showPaymentBreakdown: db.settings.showPaymentBreakdown, number: order.number, date: order.paidAt || now(), cashier: order.cashierName, type: order.type, table, guests: order.guests, orderTaker: order.orderTakerName, customer: order.customerName, mobile: order.mobile, addressLine: order.address, lines: order.lines, totals: t, payments: order.payments || [] }; }
function upsertList(res, db, user, key, body, action) { let record = body; if (!record.id) { record.id = uid(key.slice(0,3)); db[key].push(record); } else { const i = db[key].findIndex(x => x.id === record.id); if (i >= 0) db[key][i] = { ...db[key][i], ...record }; else db[key].push(record); } audit(db, user, action, { id: record.id, name: record.name }); saveDb(db); return send(res, 200, { ok: true, record }); }

async function handleApi(req, res, pathname, query) {
  const db = loadDb();
  try {
    if (pathname === '/api/login' && req.method === 'POST') { const body = await parseBody(req); const user = db.users.find(u => u.email.toLowerCase() === String(body.email || '').toLowerCase() && u.password === body.password && u.active); if (!user) return send(res, 401, { ok: false, error: 'Invalid login' }); const token = crypto.randomBytes(24).toString('hex'); TOKENS.set(token, { userId: user.id, createdAt: Date.now() }); audit(db, user, 'LOGIN', { email: user.email }); saveDb(db); return send(res, 200, { ok: true, token, user: publicUser(db, user) }); }
    const user = requireAuth(req, db);
    if (pathname === '/api/state') return send(res, 200, { ok: true, data: compactState(db, user) });

    if (pathname === '/api/upload-image' && req.method === 'POST') { requirePerm(db, user, 'admin.menu'); const body = await parseBody(req); const match = String(body.dataUrl || '').match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/); if (!match) throw Object.assign(new Error('Invalid image data'), { status: 422 }); const ext = match[1].split('/')[1].replace('jpeg', 'jpg'); const file = `${Date.now()}-${safeName(body.filename || 'image').replace(/\.[a-z0-9]+$/i, '')}.${ext}`; ensureDir(path.join(PUBLIC_DIR, 'uploads')); fs.writeFileSync(path.join(PUBLIC_DIR, 'uploads', file), Buffer.from(match[2], 'base64')); audit(db, user, 'IMAGE_UPLOADED', { file, futureTarget: 'Cloudflare R2' }); saveDb(db); return send(res, 200, { ok: true, url: `/uploads/${file}`, key: file }); }

    if (pathname === '/api/shift/open' && req.method === 'POST') { requirePerm(db, user, 'pos.pay'); const body = await parseBody(req); if (activeShift(db)) throw Object.assign(new Error('A shift is already open'), { status: 409 }); const shift = { id: uid('shf'), number: db.shifts.length + 1, status: 'OPEN', cashierId: user.id, cashierName: user.name, openingCash: money(body.openingCash), openedAt: now() }; db.shifts.push(shift); audit(db, user, 'SHIFT_OPENED', shift); saveDb(db); return send(res, 200, { ok: true, shift }); }
    if (pathname === '/api/shift/close' && req.method === 'POST') { requirePerm(db, user, 'pos.pay'); const body = await parseBody(req); const shift = activeShift(db); if (!shift) throw Object.assign(new Error('No open shift'), { status: 409 }); const rd = reportData(db, { from: shift.openedAt.slice(0,10), to: now().slice(0,10), shiftId: shift.id }); const cashSales = rd.paymentWise.Cash || 0; shift.status = 'CLOSED'; shift.countedCash = money(body.countedCash); shift.expectedCash = money(Number(shift.openingCash) + cashSales); shift.difference = money(shift.countedCash - shift.expectedCash); shift.closedAt = now(); audit(db, user, 'SHIFT_CLOSED', shift); saveDb(db); return send(res, 200, { ok: true, shift }); }

    if (pathname === '/api/orders/create' && req.method === 'POST') { requirePerm(db, user, 'pos.create'); const b = await parseBody(req); if (!['DINE_IN','DELIVERY','TAKEAWAY'].includes(b.type)) throw Object.assign(new Error('Invalid order type'), { status: 422 }); if (b.type === 'DINE_IN') { if (!b.tableId) throw Object.assign(new Error('Dine In order requires table selection'), { status: 422 }); const table = db.tables.find(t => t.id === b.tableId && t.active); if (!table) throw Object.assign(new Error('Selected table not found'), { status: 404 }); const busy = db.orders.find(o => ['OPEN','HELD'].includes(o.status) && o.type === 'DINE_IN' && o.tableId === b.tableId); if (busy) throw Object.assign(new Error('This table already has an active order'), { status: 409 }); } const taker = db.orderTakers.find(t => t.id === b.orderTakerId); const createdAt = now(); const order = { id: uid('ord'), number: orderNumber(db), type: b.type, status: 'OPEN', tableId: b.type === 'DINE_IN' ? b.tableId : null, guests: b.type === 'DINE_IN' ? Number(b.guests || 1) : 0, orderTakerId: b.orderTakerId || null, orderTakerName: taker?.name || '', customerName: b.customerName || '', mobile: b.mobile || '', address: b.address || '', deliveryNotes: b.deliveryNotes || '', deliveryFee: b.type === 'DELIVERY' ? money(b.deliveryFee ?? db.settings.defaultDeliveryFee) : 0, lines: [], discountType: 'NONE', discountValue: 0, createdAt, tableOccupiedAt: b.type === 'DINE_IN' ? createdAt : null, cashierId: user.id, cashierName: user.name, timeline: [{ event: 'CREATED', at: createdAt, by: user.name }] }; db.orders.push(order); audit(db, user, 'ORDER_CREATED', { orderId: order.id, number: order.number, type: order.type }); saveDb(db); return send(res, 200, { ok: true, order }); }
    if (pathname === '/api/orders/save' && req.method === 'POST') { requirePerm(db, user, 'pos.edit'); const b = await parseBody(req); const order = db.orders.find(o => o.id === b.id); if (!order) throw Object.assign(new Error('Order not found'), { status: 404 }); if (order.status === 'PAID') throw Object.assign(new Error('Paid order cannot be edited'), { status: 409 }); const nextType = b.type || order.type; const nextTableId = b.tableId ?? order.tableId; if (nextType === 'DINE_IN' && !nextTableId) throw Object.assign(new Error('Dine In order requires table selection'), { status: 422 }); const oldTable = order.tableId; if (nextType === 'DINE_IN' && nextTableId && nextTableId !== order.tableId) { const table = db.tables.find(t => t.id === nextTableId && t.active); if (!table) throw Object.assign(new Error('Selected table not found'), { status: 404 }); const busy = db.orders.find(o => o.id !== order.id && ['OPEN','HELD'].includes(o.status) && o.type === 'DINE_IN' && o.tableId === nextTableId); if (busy) throw Object.assign(new Error('Target table is busy'), { status: 409 }); } Object.assign(order, { type: nextType, tableId: nextType === 'DINE_IN' ? nextTableId : null, guests: nextType === 'DINE_IN' ? Number((b.guests ?? order.guests) || 1) : 0, orderTakerId: b.orderTakerId ?? order.orderTakerId, orderTakerName: b.orderTakerName ?? order.orderTakerName, customerName: b.customerName ?? order.customerName, mobile: b.mobile ?? order.mobile, address: b.address ?? order.address, deliveryFee: nextType === 'DELIVERY' ? money(b.deliveryFee ?? order.deliveryFee) : 0, lines: Array.isArray(b.lines) ? b.lines : order.lines, discountType: b.discountType || order.discountType, discountValue: money(b.discountValue ?? order.discountValue), updatedAt: now() }); if (order.type === 'DINE_IN' && order.tableId && !order.tableOccupiedAt) order.tableOccupiedAt = oldTable && oldTable !== order.tableId ? (order.createdAt || now()) : now(); if (oldTable && oldTable !== order.tableId) order.timeline.push({ event: 'TABLE_TRANSFERRED', at: now(), by: user.name, from: oldTable, to: order.tableId }); if (b.hold) { requirePerm(db, user, 'pos.hold'); order.status = 'HELD'; order.heldAt = now(); order.timeline.push({ event: 'HELD', at: now(), by: user.name }); } else order.status = 'OPEN'; audit(db, user, b.hold ? 'ORDER_HELD' : 'ORDER_SAVED', { orderId: order.id, number: order.number }); saveDb(db); return send(res, 200, { ok: true, order, totals: totals(order) }); }
    if (pathname === '/api/orders/pay' && req.method === 'POST') { requirePerm(db, user, 'pos.pay'); const b = await parseBody(req); const order = db.orders.find(o => o.id === b.id); if (!order) throw Object.assign(new Error('Order not found'), { status: 404 }); if (order.status === 'PAID') throw Object.assign(new Error('Order already paid'), { status: 409 }); if (order.type === 'DINE_IN' && !order.tableId) throw Object.assign(new Error('Dine In order requires table before payment'), { status: 422 }); if (Array.isArray(b.lines)) order.lines = b.lines; order.discountType = b.discountType || order.discountType; order.discountValue = money(b.discountValue ?? order.discountValue); order.deliveryFee = order.type === 'DELIVERY' ? money(b.deliveryFee ?? order.deliveryFee) : 0; const t = totals(order); const payments = (b.payments || []).filter(p => Number(p.amount) > 0).map(p => ({ method: p.method, amount: money(p.amount), reference: p.reference || '', received: money(p.received || p.amount), change: money(p.change || 0) })); const paid = money(payments.reduce((s,p) => s + p.amount, 0)); if (paid < t.total) throw Object.assign(new Error('Payment amount is less than total'), { status: 422 }); order.payments = payments; order.status = 'PAID'; order.paidAt = now(); order.tableReleasedAt = now(); order.timeline.push({ event: 'PAID', at: now(), by: user.name, total: t.total }); audit(db, user, 'ORDER_PAID', { orderId: order.id, number: order.number, total: t.total, payments }); saveDb(db); return send(res, 200, { ok: true, order, totals: t, receipt: buildReceipt(db, order) }); }
    if (pathname === '/api/orders/void' && req.method === 'POST') { requirePerm(db, user, 'pos.void'); const b = await parseBody(req); requireManager(db, b.managerPin); const order = db.orders.find(o => o.id === b.id); if (!order) throw Object.assign(new Error('Order not found'), { status: 404 }); order.status = 'VOID'; order.voidedAt = now(); order.voidReason = b.reason || 'Manager void'; order.timeline.push({ event: 'VOIDED', at: now(), by: user.name, reason: order.voidReason }); audit(db, user, 'ORDER_VOIDED', { orderId: order.id, number: order.number, reason: order.voidReason }); saveDb(db); return send(res, 200, { ok: true, order }); }
    if (pathname === '/api/orders/refund' && req.method === 'POST') { requirePerm(db, user, 'pos.refund'); const b = await parseBody(req); requireManager(db, b.managerPin); const order = db.orders.find(o => o.id === b.id); if (!order || order.status !== 'PAID') throw Object.assign(new Error('Paid order not found'), { status: 404 }); const amount = money(b.amount || totals(order).total); if (amount <= 0) throw Object.assign(new Error('Invalid refund amount'), { status: 422 }); const refund = { id: uid('ref'), orderId: order.id, orderNumber: order.number, amount, method: b.method || 'Cash', reason: b.reason || 'Refund', createdAt: now(), by: user.name }; db.refunds.push(refund); order.timeline.push({ event: 'REFUNDED', at: now(), by: user.name, amount }); audit(db, user, 'ORDER_REFUNDED', refund); saveDb(db); return send(res, 200, { ok: true, refund }); }

    if (pathname === '/api/admin/payment-correction' && req.method === 'POST') {
      requirePerm(db, user, 'pos.payment_correction');
      const b = await parseBody(req);
      requireManager(db, b.managerPin);
      const order = db.orders.find(o => o.id === b.id);
      if (!order || order.status !== 'PAID') throw Object.assign(new Error('Paid order not found'), { status: 404 });
      const t = totals(order);
      const cash = money(b.cash || 0), card = money(b.card || 0), online = money(b.online || 0);
      const received = money(cash + card + online);
      const remaining = money(t.total - received);
      if (remaining > 0) throw Object.assign(new Error(`Payment amount is less than total by Rs ${remaining}`), { status: 422 });
      const extra = money(Math.max(0, received - t.total));
      if (extra > 0 && cash < extra) throw Object.assign(new Error('Extra amount must be cash so change can be returned'), { status: 422 });
      const cashRevenue = money(Math.max(0, cash - extra));
      const before = order.payments || [];
      order.payments = [
        { method: 'Cash', amount: cashRevenue, received: cash, change: extra },
        { method: 'Card', amount: card, received: card, change: 0 },
        { method: 'Online', amount: online, received: online, change: 0 }
      ].filter(p => p.amount > 0 || p.received > 0);
      order.timeline.push({ event: 'PAYMENT_CORRECTED', at: now(), by: user.name, before, after: order.payments });
      audit(db, user, 'PAYMENT_CORRECTED', { orderId: order.id, number: order.number, before, after: order.payments });
      saveDb(db);
      return send(res, 200, { ok: true, order, receipt: buildReceipt(db, order) });
    }
    if (pathname === '/api/admin/reopen-paid' && req.method === 'POST') {
      requirePerm(db, user, 'pos.payment_correction');
      const b = await parseBody(req);
      requireManager(db, b.managerPin);
      const order = db.orders.find(o => o.id === b.id);
      if (!order || order.status !== 'PAID') throw Object.assign(new Error('Paid order not found'), { status: 404 });
      if (order.type === 'DINE_IN' && order.tableId) {
        const busy = db.orders.find(o => o.id !== order.id && ['OPEN','HELD'].includes(o.status) && o.type === 'DINE_IN' && o.tableId === order.tableId);
        if (busy) throw Object.assign(new Error('Original table is busy with another open order'), { status: 409 });
      }
      order.previousPaidSnapshot = { paidAt: order.paidAt, payments: order.payments || [], tableReleasedAt: order.tableReleasedAt };
      order.payments = [];
      order.status = 'OPEN';
      order.reopenedAt = now();
      order.paidAt = null;
      order.tableReleasedAt = null;
      if (order.type === 'DINE_IN' && order.tableId && !order.tableOccupiedAt) order.tableOccupiedAt = order.createdAt || now();
      order.timeline.push({ event: 'REOPENED_FOR_EDIT', at: now(), by: user.name });
      audit(db, user, 'PAID_ORDER_REOPENED', { orderId: order.id, number: order.number });
      saveDb(db);
      return send(res, 200, { ok: true, order });
    }

    if (pathname.startsWith('/api/admin/') && req.method === 'POST') { const b = await parseBody(req); const action = pathname.split('/').pop(); if (['category','item','deal'].includes(action)) { requirePerm(db, user, 'admin.menu'); return upsertList(res, db, user, action === 'category' ? 'categories' : action === 'item' ? 'items' : 'deals', b, `${action.toUpperCase()}_SAVED`); } if (action === 'payment') { requirePerm(db, user, 'admin.payments'); return upsertList(res, db, user, 'paymentMethods', b, 'PAYMENT_METHOD_SAVED'); } if (action === 'table') { requirePerm(db, user, 'admin.tables'); return upsertList(res, db, user, 'tables', b, 'TABLE_SAVED'); } if (action === 'taker') { requirePerm(db, user, 'admin.staff'); return upsertList(res, db, user, 'orderTakers', b, 'ORDER_TAKER_SAVED'); } if (action === 'user') { requirePerm(db, user, 'admin.users'); if (!Array.isArray(b.roleIds)) b.roleIds = b.roleId ? [b.roleId] : ['role_cashier']; return upsertList(res, db, user, 'users', b, 'USER_SAVED'); } if (action === 'role') { requirePerm(db, user, 'admin.roles'); b.permissions = Array.isArray(b.permissions) ? b.permissions.filter(p => PERMISSIONS.includes(p)) : []; return upsertList(res, db, user, 'roles', b, 'ROLE_SAVED'); } if (action === 'settings') { requirePerm(db, user, 'admin.settings'); db.settings = { ...db.settings, ...b }; audit(db, user, 'SETTINGS_SAVED', Object.keys(b)); saveDb(db); return send(res, 200, { ok: true, settings: db.settings }); } }

    if (pathname === '/api/reports' && req.method === 'GET') { requirePerm(db, user, 'reports.view'); return send(res, 200, { ok: true, data: reportData(db, query) }); }
    if (pathname === '/api/export' && req.method === 'GET') { requirePerm(db, user, 'reports.export'); const rd = reportData(db, query); const rows = [['Bill No','Date','Order Type','Table','Customer','Mobile','Order Taker','Cashier','Subtotal','Discount','Delivery Fee','Total','Payments']].concat(rd.orders.map(o => [o.number,o.date,o.type,o.table,o.customer,o.mobile,o.orderTaker,o.cashier,o.subtotal,o.discount,o.deliveryFee,o.total,o.payments])); const csv = rows.map(r => r.map(v => `"${String(v ?? '').replace(/"/g,'""')}"`).join(',')).join('\n'); return sendText(res, 200, csv, 'text/csv; charset=utf-8', { 'Content-Disposition': `attachment; filename="swifttill-report-${Date.now()}.csv"` }); }
    if (pathname === '/api/backup/download' && req.method === 'GET') { requirePerm(db, user, 'backup.manage'); audit(db, user, 'BACKUP_DOWNLOADED', { at: now() }); saveDb(db); return sendText(res, 200, JSON.stringify({ exportedAt: now(), app: 'SwiftTill POS', db }, null, 2), 'application/json; charset=utf-8', { 'Content-Disposition': `attachment; filename="swifttill-backup-${Date.now()}.json"` }); }
    if (pathname === '/api/backup/restore' && req.method === 'POST') { requirePerm(db, user, 'backup.manage'); const b = await parseBody(req); const next = b.db || b; if (!next.settings || !Array.isArray(next.orders) || !Array.isArray(next.items)) throw Object.assign(new Error('Invalid backup'), { status: 422 }); audit(next, user, 'BACKUP_RESTORED', { at: now() }); saveDb(next); return send(res, 200, { ok: true }); }
    send(res, 404, { ok: false, error: 'API not found' });
  } catch (err) { send(res, err.status || 500, { ok: false, error: err.message || 'Server error' }); }
}
function staticServe(req, res, pathname) { let filePath = pathname === '/' ? path.join(PUBLIC_DIR, 'index.html') : path.join(PUBLIC_DIR, decodeURIComponent(pathname)); if (!filePath.startsWith(PUBLIC_DIR)) return sendText(res, 403, 'Forbidden'); if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) filePath = path.join(PUBLIC_DIR, 'index.html'); const ext = path.extname(filePath).toLowerCase(); const types = { '.html':'text/html; charset=utf-8', '.css':'text/css; charset=utf-8', '.js':'application/javascript; charset=utf-8', '.png':'image/png', '.jpg':'image/jpeg', '.jpeg':'image/jpeg', '.svg':'image/svg+xml', '.ico':'image/x-icon', '.webmanifest':'application/manifest+json' }; res.writeHead(200, { 'Content-Type': types[ext] || 'application/octet-stream' }); fs.createReadStream(filePath).pipe(res); }
const server = http.createServer(async (req, res) => { const parsed = url.parse(req.url, true); if (parsed.pathname.startsWith('/api/')) return handleApi(req, res, parsed.pathname, parsed.query); staticServe(req, res, parsed.pathname); });
server.listen(PORT, () => { ensureDir(path.join(PUBLIC_DIR, 'uploads')); ensureDir(STORAGE_DIR); loadDb(); console.log(`SwiftTill POS running: http://localhost:${PORT}`); console.log('Login: admin@swifttill.local / admin123'); });
